appId: com.kodak.steptouch
---
# Assert standard settings menu items.
- extendedWaitUntil:
    visible: "Support"
    timeout: 2000
- assertVisible:
    text: "Quick tips"
    optional: true
- assertVisible:
    text: "Quick Tips"
    optional: true
- assertVisible: "Support"
- assertVisible:
    text: "Share settings"
    optional: true
- assertVisible:
    text: "Share Settings"
    optional: true
- assertVisible:
    text: ".*(?i)order paper refill.*"
    optional: true
- assertVisible:
    text: "Legal"
    optional: true
- assertVisible:
    text: "About"
    optional: true
