appId: com.kodak.steptouch
---

- runFlow: tap_settings_gear.yaml
- extendedWaitUntil:
    visible:
      text: ".*(?i)(quick tips|support|share settings|order paper refill|legal|about).*"
    timeout: 2000
